/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ExtensionRouteRouteImport } from './routes/extension/route';
import { Route as PocRouteRouteImport } from './routes/poc/route';
import { Route as SettingsRouteRouteImport } from './routes/settings/route';
import { Route as SourcesRouteRouteImport } from './routes/sources/route';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ExtensionRouteRoute = ExtensionRouteRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any);
const PocRouteRoute = PocRouteRouteImport.update({
  id: '/poc',
  path: '/poc',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const SourcesRouteRoute = SourcesRouteRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/extension': typeof ExtensionRouteRoute;
  '/poc': typeof PocRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/sources': typeof SourcesRouteRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/extension': typeof ExtensionRouteRoute;
  '/poc': typeof PocRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/sources': typeof SourcesRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/extension': typeof ExtensionRouteRoute;
  '/poc': typeof PocRouteRoute;
  '/settings': typeof SettingsRouteRoute;
  '/sources': typeof SourcesRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/extension' | '/poc' | '/settings' | '/sources';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/extension' | '/poc' | '/settings' | '/sources';
  id: '__root__' | '/' | '/extension' | '/poc' | '/settings' | '/sources';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ExtensionRouteRoute: typeof ExtensionRouteRoute;
  PocRouteRoute: typeof PocRouteRoute;
  SettingsRouteRoute: typeof SettingsRouteRoute;
  SourcesRouteRoute: typeof SourcesRouteRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/extension': {
      id: '/extension';
      path: '/extension';
      fullPath: '/extension';
      preLoaderRoute: typeof ExtensionRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/poc': {
      id: '/poc';
      path: '/poc';
      fullPath: '/poc';
      preLoaderRoute: typeof PocRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sources': {
      id: '/sources';
      path: '/sources';
      fullPath: '/sources';
      preLoaderRoute: typeof SourcesRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionRouteRoute: ExtensionRouteRoute,
  PocRouteRoute: PocRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  SourcesRouteRoute: SourcesRouteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
